import {toTags_, toTag_, tagItems_, replace_, replaceAll_, recycle_} from "../globalFns.js"

ServerEvents.recipes(event => {
    event.recipes.gtceu.centrifuge('foxtech:soul_quartz_sand')
        .itemInputs('2x gtceu:soul_quartz_sand_dust')
        .itemOutputs('1x gtceu:quartz_sand_dust', '1x mysticalagriculture:nether_essence')
        .duration(60)
        .EUt(30)
    event.recipes.gtceu.centrifuge('foxtech:clay_loam')
        .itemInputs('3x gtceu:dirt_dust')
        .itemOutputs('3x gtceu:tiny_clay_dust', '1x minecraft:sand', '1x twigs:silt') //Todo: make these dusts
        .duration(80)
        .EUt(30)
    event.recipes.gtceu.centrifuge('foxtech:mud')
        .inputFluids(Fluid.of('gtceu:mud', 1000))
        .chancedOutput('minecraft:sand', 2500, 250)
        .chancedOutput('minecraft:gravel', 2500, 250)
        .chancedOutput('minecraft:clay', 2500, 250)
        .chancedOutput('gtceu:limestone_dust', 2500, 250)
        .duration(20)
        .EUt(30)
    event.recipes.gtceu.centrifuge('foxtech:dark_prismarine')
        .itemInputs('9x gtceu:dark_prismarine_dust')
        .itemOutputs('8x minecraft:prismarine_shard', '1x gtceu:chemical_black_dye')
        .duration(20)
        .EUt(30)
})